### ISSUE TITLE
Obsługa map z tiled

### ISSUE THREAD

**Issue by sztobar** [sztobar/amsi_poli_platformer#1]
Zaimplementowanie poprawnie kolizji, assetów, początku i końca rundy.

**Comment by sztobar** [comment]
Na przykładzie mapy "mapa-wies.json" - są dwie warstwy tile'ów:
- tileset - gdzie są same widoki
- tiles properties - gdzie są kafelki określające właściwości:
  - czerwony krzyżyk - przeszkoda na której gracz się zatrzymuje
  - niebieska platforma - na którą gracz może wskoczyć (w przeciwieństwie od czerwonego krzyżyku można wskoczyć "pod nią" tj. nie działa kolizja jeśli gracz jest pod nią
  - żółte kolce - insta ded - jeszcze nie zaimplementowane
  - S, E - kafelek początek i końca rundy, dodawane w osobnej warstwie "objects"

Włączając grę możemy zobaczyć właściwości kafelków klikając spację

**Comment by kamokar** [comment]
Regards,
Kamil Karecki.

W dniu 2015-12-28 o 19:06, Bartosz Szewczyk pisze:

> Na przykładzie mapy "mapa-wies.json" - są dwie warstwy tile'ów:
> - tileset - gdzie są same widoki
> - tiles properties - gdzie są kafelki określające właściwości:
>     o czerwony krzyżyk - przeszkoda na której gracz się zatrzymuje
>     o niebieska platforma - na którą gracz może wskoczyć (w
>       przeciwieństwie od czerwonego krzyżyku można wskoczyć "pod
>       nią" tj. nie działa kolizja jeśli gracz jest pod nią
>     o żółte kolce - insta ded - jeszcze nie zaimplementowane
>     o S, E - kafelek początek i końca rundy, dodawane w osobnej
>       warstwie "objects"
> 
> Włączając grę możemy zobaczyć właściwości kafelków klikając spację
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/sztobar/amsi_poli_platformer/issues/1#issuecomment-167616351.

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by kamokar** [comment]
Po synchronizacji przestała mi działać aplikacja. Pojawia się tylko 
błękitny ekran :(

Regards,
Kamil Karecki.

W dniu 2015-12-28 o 19:06, Bartosz Szewczyk pisze:

> Na przykładzie mapy "mapa-wies.json" - są dwie warstwy tile'ów:
> - tileset - gdzie są same widoki
> - tiles properties - gdzie są kafelki określające właściwości:
>     o czerwony krzyżyk - przeszkoda na której gracz się zatrzymuje
>     o niebieska platforma - na którą gracz może wskoczyć (w
>       przeciwieństwie od czerwonego krzyżyku można wskoczyć "pod
>       nią" tj. nie działa kolizja jeśli gracz jest pod nią
>     o żółte kolce - insta ded - jeszcze nie zaimplementowane
>     o S, E - kafelek początek i końca rundy, dodawane w osobnej
>       warstwie "objects"
> 
> Włączając grę możemy zobaczyć właściwości kafelków klikając spację
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/sztobar/amsi_poli_platformer/issues/1#issuecomment-167616351.

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com
