### ISSUE TITLE
Checkpoint + chmurka

### ISSUE THREAD

**Issue by ghost** [sztobar/amsi_poli_platformer#22]
W momencie, gdy postać ginie na checkpoincie wskutek kolizji z chmurką ginie się non-stop, gdyż chmurka nie resetuje pozycji, i po każdym respawnie ginie się od nowa.

**Comment by kamokar** [comment]
Problem znany :) Można rozwiązać np. poprzez zastosowanie nieśmiertelności gracza przez np. 2 sekundy po respawnie.

**Comment by sztobar** [comment]
resolved
