### ISSUE TITLE
Sprite'y i animacja przeciwników 

### ISSUE THREAD

**Issue by sztobar** [sztobar/amsi_poli_platformer#4]
1. Wieś: 
   - biegające świnie
   - farmerzy z szotganami
   - chmura z napisem „Zapach kompostu”
2. Miasto:
   - biznesmeni rzucający łapówkami
   - chmura smogu
3. Sejm:
   - reżimowy dziennikarz
   - agenci BOR-u
   - chmurka z napisem Korupcja
4. Europarlament
   - polityk z transparentem z sercem
   - polityk strzelający symbolami parafafu
   - chmura z napisaem "Poprawność polityczna"

**Comment by sztobar** [comment]
@lukaszopara  i @kamokar musicie jakoś podzielić się zadaniami ponieważ przeciwników jest dużo do zrobienia.

**Comment by kamokar** [comment]
Wieś - enemies sprites completed

**Comment by kamokar** [comment]
Miasto - enemies sprites completed: 
biznesmeni rzucający łapówkami
chmura smogu
deskorolkarze

**Comment by kamokar** [comment]
Sejm - completed

journalist
bor
chmurka z napisem Korupcja

**Comment by kamokar** [comment]
Europarlament - completed

Juncker
Mogherini
chmura z napisem "Poprawność polityczna"
