### ISSUE TITLE
Sprite'y i animacja bohaterów

### ISSUE THREAD

**Issue by sztobar** [sztobar/amsi_poli_platformer#5]
Przemysław Wipler
Antoni Macierewicz
Grzegorz Braun
Liroy

**Comment by kamokar** [comment]
![liroy](https://cloud.githubusercontent.com/assets/11929809/11981026/5e210596-a99f-11e5-84eb-dacaf90ab1ee.png)

**Comment by kamokar** [comment]
final version of liroy

**Comment by kamokar** [comment]
![macierewiczpng](https://cloud.githubusercontent.com/assets/11929809/11985250/fe59abf8-a9c2-11e5-9f29-dd56eb71be0f.png)
Macierewicz sprite

**Comment by kamokar** [comment]
![wippler](https://cloud.githubusercontent.com/assets/11929809/11986327/8b261bb0-a9ce-11e5-9def-5d6777138bde.png)
Wippler sprite

**Comment by kamokar** [comment]
Completed

**Comment by kamokar** [comment]
Completed all character's animation frames: walking, dieing, shooting.
